name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (set base to project path)
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_MATRIX_ID: ${{ secrets.VITE_MATRIX_ID }}
          VITE_COLLABORATOR_EMAIL: ${{ secrets.VITE_COLLABORATOR_EMAIL }}
        # Replace "/REPO_NAME/" with your repository name for a project site.
        run: npm run build -- --base "/pre-adjudication-matrix-configuration/"

      - name: Create 404 fallback (SPA support)
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist